import { Staff, OvertimeRecord } from "./types";

export const SAMPLE_STAFF: Staff[] = [
  {
    "id": "st-1",
    "namaAllStaff": "SAMUEL BOANARGES",
    "nomorPasport": "**VVIP**",
    "jabatanPosisi": "LEADER",
    "emailDrive": "samuelboan.smb88@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "V I P",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "",
    "seasonRumahIbadah": "",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-2",
    "namaAllStaff": "FADLAN PRATAMA TAMBUNAN",
    "nomorPasport": "C6814592",
    "jabatanPosisi": "CS",
    "emailDrive": "wdbosfadlanpratama@gmail.com",
    "emailBk": "wdbosfadlanpratama@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "SINGKAWANG",
    "idLine": "FADLAN",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "SINGKAWANG",
    "notes": ""
  },
  {
    "id": "st-3",
    "namaAllStaff": "EVRI SIHITE",
    "nomorPasport": "C7919675",
    "jabatanPosisi": "CS",
    "emailDrive": "evrisihite975@gmail.com",
    "emailBk": "evrisihite975@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "SIDIKALANG",
    "idLine": "EVRISIHITE",
    "seasonRumahIbadah": "SEASON 3",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "SIDIKALANG",
    "notes": ""
  },
  {
    "id": "st-4",
    "namaAllStaff": "DWI ARIYANTO",
    "nomorPasport": "X7836795",
    "jabatanPosisi": "CS",
    "emailDrive": "dwiariyanto9956@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-5",
    "namaAllStaff": "ZIKRI TRIANSYAH KAMAL",
    "nomorPasport": "E7722009",
    "jabatanPosisi": "CS",
    "emailDrive": "zikritriansyahkamal251@gmail.com",
    "emailBk": "zikritriansyahkamal251@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-6",
    "namaAllStaff": "NICO FEBRIAN",
    "nomorPasport": "E3163410",
    "jabatanPosisi": "CS",
    "emailDrive": "nicofebrian120623@gmail.com",
    "emailBk": "nicofebrian120623@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "PONTIANAK",
    "idLine": "Nico",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PONTIANAK",
    "notes": ""
  },
  {
    "id": "st-7",
    "namaAllStaff": "GILBERTO ANGELINO",
    "nomorPasport": "C9252203",
    "jabatanPosisi": "CS",
    "emailDrive": "gilbertoangelino117@gmail.com",
    "emailBk": "gilbertoangelino117@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "JAKARTA",
    "idLine": "Gilbert",
    "seasonRumahIbadah": "SEASON 3",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "JAKARTA",
    "notes": ""
  },
  {
    "id": "st-8",
    "namaAllStaff": "HENGKI",
    "nomorPasport": "E2612730",
    "jabatanPosisi": "CS",
    "emailDrive": "hengkikeker17@gmail.com",
    "emailBk": "hengkikeker17@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "TEBAS",
    "idLine": "HENGKI",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "TEBAS",
    "notes": ""
  },
  {
    "id": "st-9",
    "namaAllStaff": "TAUFAN KHATULISTIWA",
    "nomorPasport": "E2406129",
    "jabatanPosisi": "CS",
    "emailDrive": "taufankhatulistiwa821@gmail.com",
    "emailBk": "taufankhatulistiwa821@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "SURABAYA",
    "idLine": "Taufankhatulistiwa",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "SURABAYA",
    "notes": ""
  },
  {
    "id": "st-10",
    "namaAllStaff": "ERIC SYAHPUTRA",
    "nomorPasport": "E5525035",
    "jabatanPosisi": "CS",
    "emailDrive": "ericsyahputra051223@gmail.com",
    "emailBk": "ericsyahputra051223@gmail.com",
    "status": "CUTI",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "LUBUK PAKAM",
    "idLine": "Eric.S",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "LUBUK PAKAM",
    "notes": ""
  },
  {
    "id": "st-11",
    "namaAllStaff": "SAZU SAHPUTRA",
    "nomorPasport": "C8490663",
    "jabatanPosisi": "CS",
    "emailDrive": "sazusahputra546@gmail.com",
    "emailBk": "sazusahputra546@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "sazusahputra",
    "seasonRumahIbadah": "SEASON 3",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-12",
    "namaAllStaff": "DIVA DAWWAS",
    "nomorPasport": "X9302197",
    "jabatanPosisi": "CS",
    "emailDrive": "divadwas.smb88@gmail.com",
    "emailBk": "divadwas.smb88@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "dievadawwas'",
    "seasonRumahIbadah": "SEASON 3",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-13",
    "namaAllStaff": "MUHAMMAD RIO AFRIZA",
    "nomorPasport": "C7776080",
    "jabatanPosisi": "CS",
    "emailDrive": "rioafriza5412@gmail.com",
    "emailBk": "rioafriza5412@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "medan",
    "idLine": "m rio",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "medan",
    "notes": ""
  },
  {
    "id": "st-14",
    "namaAllStaff": "ADITYA PANCA NUGRAHA",
    "nomorPasport": "E2929201",
    "jabatanPosisi": "CS",
    "emailDrive": "adityapanca3103@gmail.com",
    "emailBk": "adityapanca3103@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-15",
    "namaAllStaff": "SURAJ KUMAR",
    "nomorPasport": "E1714955",
    "jabatanPosisi": "CS",
    "emailDrive": "surajkumaraja1945@gmail.com",
    "emailBk": "surajkumaraja19451@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "SURAJ",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-16",
    "namaAllStaff": "JOESQUENSEND GAVEROND",
    "nomorPasport": "X2837768",
    "jabatanPosisi": "CS",
    "emailDrive": "jgaverond@gmail.com",
    "emailBk": "jgaverond@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "PANGKAL PINANG",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PANGKAL PINANG",
    "notes": ""
  },
  {
    "id": "st-17",
    "namaAllStaff": "ANDRE EVANDRO GINTING",
    "nomorPasport": "E3524180",
    "jabatanPosisi": "CS",
    "emailDrive": "evandroandre888@gmail.com",
    "emailBk": "andre030524@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-18",
    "namaAllStaff": "VERRI AYANG",
    "nomorPasport": "E2929082",
    "jabatanPosisi": "CS",
    "emailDrive": "verriayang88.smb88@gmail.com",
    "emailBk": "verriayangbk88@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN PANTAI LABU",
    "idLine": "verriayang",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN PANTAI LABU",
    "notes": ""
  },
  {
    "id": "st-19",
    "namaAllStaff": "MUHAMMAD ANDRI AZMI",
    "nomorPasport": "E2867309",
    "jabatanPosisi": "CS",
    "emailDrive": "azmimuhammadandri@gmail.com",
    "emailBk": "azmimuhammadandri@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "KLAMBIR 5 MEDAN",
    "idLine": "muhammad andri azmi",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "KLAMBIR 5 MEDAN",
    "notes": ""
  },
  {
    "id": "st-20",
    "namaAllStaff": "FENNY PURWANDARI",
    "nomorPasport": "E2375173",
    "jabatanPosisi": "CS",
    "emailDrive": "fennypurwandari122@gmail.com",
    "emailBk": "fennypurwandari122@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN MARELAN",
    "idLine": "FENNY WANDARI",
    "seasonRumahIbadah": "SEASON 4",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN MARELAN",
    "notes": ""
  },
  {
    "id": "st-21",
    "namaAllStaff": "RENATAN",
    "nomorPasport": "E5152033",
    "jabatanPosisi": "CS",
    "emailDrive": "renatan131223@gmail.com",
    "emailBk": "renatan131223@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "PONTIANAK",
    "idLine": "RENATAN",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PONTIANAK",
    "notes": ""
  },
  {
    "id": "st-22",
    "namaAllStaff": "LEO JONATHAN LIM",
    "nomorPasport": "C9041353",
    "jabatanPosisi": "CS",
    "emailDrive": "LEOJONATHAN15082024@gmail.com",
    "emailBk": "LEOJONATHAN15082024@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-23",
    "namaAllStaff": "NICO ADRIANSYAH HUTAGAOL",
    "nomorPasport": "X6653631",
    "jabatanPosisi": "CS",
    "emailDrive": "nicoadriansyahh@gmail.com",
    "emailBk": "nicoadriansyahh@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-24",
    "namaAllStaff": "ARJUN",
    "nomorPasport": "E2214449",
    "jabatanPosisi": "CS",
    "emailDrive": "arjunaja1945@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "ARJUN",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-25",
    "namaAllStaff": "DIVA SAPUTRA",
    "nomorPasport": "X7906822",
    "jabatanPosisi": "CS",
    "emailDrive": "divasaputraaa88@gmail.com",
    "emailBk": "divasaputraaa88@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "DIVA SAPUTRA",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-26",
    "namaAllStaff": "RONNY",
    "nomorPasport": "X2658487",
    "jabatanPosisi": "CS",
    "emailDrive": "ronny270424@gmail.com",
    "emailBk": "ronny270424@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "Pontianak",
    "idLine": "Ronny",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "Pontianak",
    "notes": ""
  },
  {
    "id": "st-27",
    "namaAllStaff": "HARIS RIZALDY ARUAN",
    "nomorPasport": "E4098434",
    "jabatanPosisi": "CS",
    "emailDrive": "harisrizaldyaruan@gmail.com",
    "emailBk": "harisrizaldyaruan@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "Tanjung morawa",
    "idLine": "Teguh Andrean",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "Tanjung morawa",
    "notes": ""
  },
  {
    "id": "st-28",
    "namaAllStaff": "AFIF RAIS",
    "nomorPasport": "E3504038",
    "jabatanPosisi": "CS",
    "emailDrive": "afifrais33@gmail.com",
    "emailBk": "afifrais33@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "HARIS RIZALDY ARUAN",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-29",
    "namaAllStaff": "MUHAMMAD AUDI SOFIAN",
    "nomorPasport": "X7905920",
    "jabatanPosisi": "CS",
    "emailDrive": "audisofian1945@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "ROOM 7 VIP",
    "asalKota": "MEDAN",
    "idLine": "Rais",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-30",
    "namaAllStaff": "MUHAMMAD FACHRI",
    "nomorPasport": "E7092105",
    "jabatanPosisi": "CS",
    "emailDrive": "muhammadfachri15082024@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-31",
    "namaAllStaff": "S G KEVINDRA NAIDU",
    "nomorPasport": "E3503037",
    "jabatanPosisi": "CS",
    "emailDrive": "Kevindranaidu55@gmail.com",
    "emailBk": "kevindranaidu55@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-32",
    "namaAllStaff": "MORIS BILIEVE GINTING",
    "nomorPasport": "E5801583",
    "jabatanPosisi": "CS",
    "emailDrive": "morisginting120224@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "CHULBUL",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-33",
    "namaAllStaff": "DIAZ HERMAWAN",
    "nomorPasport": "X2726247",
    "jabatanPosisi": "CS",
    "emailDrive": "diazhermawan93@gmail.com",
    "emailBk": "diazhermawan93@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-34",
    "namaAllStaff": "NURIL ABSHAR",
    "nomorPasport": "E5380748",
    "jabatanPosisi": "CS",
    "emailDrive": "nurilabshar.smb88@gmail.com",
    "emailBk": "nurilabshar.smb88@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "RIAU",
    "idLine": "DIAZ",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "RIAU",
    "notes": ""
  },
  {
    "id": "st-35",
    "namaAllStaff": "ADITYA RIWANA",
    "nomorPasport": "E0913677",
    "jabatanPosisi": "CS",
    "emailDrive": "adityariwana250326@gmail.com",
    "emailBk": "adityariwana250326@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "ACEH",
    "idLine": "NURIIL94",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "ACEH",
    "notes": ""
  },
  {
    "id": "st-36",
    "namaAllStaff": "FERI ADYANTO",
    "nomorPasport": "E5862182",
    "jabatanPosisi": "CS",
    "emailDrive": "feriadyanto2@gmail.com",
    "emailBk": "feriadyanto2@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "PONTIANAK",
    "idLine": "",
    "seasonRumahIbadah": "-",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PONTIANAK",
    "notes": ""
  },
  {
    "id": "st-37",
    "namaAllStaff": "RINITA SOFIAN",
    "nomorPasport": "E0536455",
    "jabatanPosisi": "CS",
    "emailDrive": "rinita.smb88@gmail.com",
    "emailBk": "rinita.smb88@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "Padang",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 1",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "Padang",
    "notes": ""
  },
  {
    "id": "st-38",
    "namaAllStaff": "MAHESTA RAZ",
    "nomorPasport": "E1757678",
    "jabatanPosisi": "KAPTEN KASIR",
    "emailDrive": "mahestaraz1532@gmail.com",
    "emailBk": "mahestaraz1532@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "mahesta",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-39",
    "namaAllStaff": "ANDRE BAYU WARDANA",
    "nomorPasport": "C8255340",
    "jabatanPosisi": "KAPTEN KASIR",
    "emailDrive": "andrebayuwar5465@gmail.com",
    "emailBk": "andrebayuwar5465@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "BERINGIN",
    "idLine": "ANDRE BAYU",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BERINGIN",
    "notes": ""
  },
  {
    "id": "st-40",
    "namaAllStaff": "JUAN ANDRE PANJAITAN",
    "nomorPasport": "E2366520",
    "jabatanPosisi": "KAPTEN KASIR",
    "emailDrive": "juanandrepanjaitan@gmail.com",
    "emailBk": "juanandrepanjaitan@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "SIANTAR",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "SIANTAR",
    "notes": ""
  },
  {
    "id": "st-41",
    "namaAllStaff": "TERANGTA SEMBIRING",
    "nomorPasport": "E6754459",
    "jabatanPosisi": "KAPTEN KASIR",
    "emailDrive": "terangtasembiring17@gmail.com",
    "emailBk": "terangtasembiring17@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "BERASTAGI",
    "idLine": "TERANGTA SEMBIRING",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BERASTAGI",
    "notes": ""
  },
  {
    "id": "st-42",
    "namaAllStaff": "FAISAL SABARYANTO",
    "nomorPasport": "E2818631",
    "jabatanPosisi": "KAPTEN KASIR",
    "emailDrive": "faisalsabaryanto44@gmail.com",
    "emailBk": "faisalsabaryanto44@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "PONTIANAK",
    "idLine": "FAISAL SABARYANTO",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PONTIANAK",
    "notes": ""
  },
  {
    "id": "st-43",
    "namaAllStaff": "YOGI PERLIAN SYAHPUTRA",
    "nomorPasport": "E4159055",
    "jabatanPosisi": "KAPTEN KASIR",
    "emailDrive": "perliansyahputrayogi@gmail.com",
    "emailBk": "perliansyahputrayogi8@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN MABAR",
    "idLine": "Yogiperlian",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN MABAR",
    "notes": ""
  },
  {
    "id": "st-44",
    "namaAllStaff": "MOHD REZA PAHLEVI",
    "nomorPasport": "E7467387",
    "jabatanPosisi": "KASIR",
    "emailDrive": "rezapahlevi.smb888@gmail.com",
    "emailBk": "rezapahlevismb888@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "LANGSA",
    "idLine": "a1a2a3",
    "seasonRumahIbadah": "SEASON 1",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "LANGSA",
    "notes": ""
  },
  {
    "id": "st-45",
    "namaAllStaff": "PRIYYA SONALY",
    "nomorPasport": "E1986789",
    "jabatanPosisi": "KASIR",
    "emailDrive": "priyasonaly888@gmail.com",
    "emailBk": "priyasonaly888@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "PRIYYA",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-46",
    "namaAllStaff": "JAMENDRA PERANGIN ANGIN",
    "nomorPasport": "E2864468",
    "jabatanPosisi": "KASIR",
    "emailDrive": "jamendraperanginangin54@gmail.com",
    "emailBk": "jamendrabk@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "JAMENDRA",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-47",
    "namaAllStaff": "MUHAMMAD FAHRI KURNIAWAN",
    "nomorPasport": "C8489725",
    "jabatanPosisi": "KASIR",
    "emailDrive": "fahrikurniawanm29@gmail.com",
    "emailBk": "fahrikurniawanm291@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "MUHAMMAD FAHRI KURNIAWAN",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-48",
    "namaAllStaff": "MUHAMMAD FAHRI",
    "nomorPasport": "E1475020",
    "jabatanPosisi": "KASIR",
    "emailDrive": "muhammadfahri26845@gmail.com",
    "emailBk": "muhammadfahri061023@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "FAHRI",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-49",
    "namaAllStaff": "MUH MARWIANTO",
    "nomorPasport": "C8479150",
    "jabatanPosisi": "KASIR",
    "emailDrive": "MUHMARWIMERDEKA@gmail.com",
    "emailBk": "MUHMARWIMERDEKA@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "NTB",
    "idLine": "MUH MARWIANTO",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "NTB",
    "notes": ""
  },
  {
    "id": "st-50",
    "namaAllStaff": "SITI WAHYUNINGSIH",
    "nomorPasport": "E1509185",
    "jabatanPosisi": "KASIR",
    "emailDrive": "siti310324@gmail.com",
    "emailBk": "siti310324@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "BATAM",
    "idLine": "WAHYUNINGSIH SITI",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BATAM",
    "notes": ""
  },
  {
    "id": "st-51",
    "namaAllStaff": "TANIA WIRANTI",
    "nomorPasport": "E6253452",
    "jabatanPosisi": "KASIR",
    "emailDrive": "TANIAWIRANTI09042024@gmail.com",
    "emailBk": "TANIAWIRANTI09042024@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "TANIA WIRANTI",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-52",
    "namaAllStaff": "MUHAMMAD GHAZALI",
    "nomorPasport": "C8543472",
    "jabatanPosisi": "KASIR",
    "emailDrive": "muhammadghazali1523@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "TELUK DALAM",
    "idLine": "Muhammad ghazali",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "TELUK DALAM",
    "notes": ""
  },
  {
    "id": "st-53",
    "namaAllStaff": "IQBAL ILHAM PRATAMA TAMBOKAN",
    "nomorPasport": "E7179734",
    "jabatanPosisi": "KASIR",
    "emailDrive": "ipratamatambokan@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "STABAT",
    "idLine": "IQBAL ILHAM PRATAMA TAMBOKAN",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "STABAT",
    "notes": ""
  },
  {
    "id": "st-54",
    "namaAllStaff": "WINDA AGUSTIA",
    "nomorPasport": "E7647231",
    "jabatanPosisi": "KASIR",
    "emailDrive": "windaagustia247@gmail.com",
    "emailBk": "windaagustia247@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "WINDAGST",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-55",
    "namaAllStaff": "DONI SAPUTRA NAHAMPUN",
    "nomorPasport": "E7694440",
    "jabatanPosisi": "KASIR",
    "emailDrive": "donisaputranahampun93@gmail.com",
    "emailBk": "donisaputranahampun93@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "BASRA",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BASRA",
    "notes": ""
  },
  {
    "id": "st-56",
    "namaAllStaff": "CINDY SAPUTRI",
    "nomorPasport": "X7900967",
    "jabatanPosisi": "KASIR",
    "emailDrive": "cindysaputri7540@gmail.com",
    "emailBk": "cindysaputri754@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "LUBUK PAKAM",
    "idLine": "CINDYSAPUTRI",
    "seasonRumahIbadah": "SEASON 2",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "LUBUK PAKAM",
    "notes": ""
  },
  {
    "id": "st-57",
    "namaAllStaff": "SADINA NST",
    "nomorPasport": "E7530733",
    "jabatanPosisi": "KASIR",
    "emailDrive": "sadinanst5@gmail.com",
    "emailBk": "sadinanst5@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-58",
    "namaAllStaff": "MUHLIS",
    "nomorPasport": "E5049051",
    "jabatanPosisi": "KASIR",
    "emailDrive": "muhlisaja1112@gmail.com",
    "emailBk": "muhlisaja1112@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "Pantai Labu",
    "idLine": "Muhlis",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "Pantai Labu",
    "notes": ""
  },
  {
    "id": "st-59",
    "namaAllStaff": "SAHARUDDIN",
    "nomorPasport": "X3673527",
    "jabatanPosisi": "KASIR",
    "emailDrive": "saharuddin2025@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "TANJUNGPINANG",
    "idLine": "SAHARUDDIN",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "TANJUNGPINANG",
    "notes": ""
  },
  {
    "id": "st-60",
    "namaAllStaff": "ENDY LIE",
    "nomorPasport": "E8451705",
    "jabatanPosisi": "KASIR",
    "emailDrive": "endylie010125@gmail.com",
    "emailBk": "endylie010125@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-61",
    "namaAllStaff": "MUHAMMAD AZRI",
    "nomorPasport": "E8726881",
    "jabatanPosisi": "KASIR",
    "emailDrive": "muhammadazri010125@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "MUHAMMAD AZRI",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-62",
    "namaAllStaff": "MOYNITA CHRISMA SEMBIRING",
    "nomorPasport": "E0621159",
    "jabatanPosisi": "KASIR",
    "emailDrive": "moynitachrismasembiring@gmail.com",
    "emailBk": "moynitachrismasembiring@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "MOY",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-63",
    "namaAllStaff": "PRITA GUSTINI",
    "nomorPasport": "X4723273",
    "jabatanPosisi": "KASIR",
    "emailDrive": "pritagustini010125@gmail.com",
    "emailBk": "pritagustini010125@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "BOGOR",
    "idLine": "PRITA GUSTINI",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BOGOR",
    "notes": ""
  },
  {
    "id": "st-64",
    "namaAllStaff": "ADINDA RAPMAYANI MANURUNG",
    "nomorPasport": "E8157935",
    "jabatanPosisi": "KASIR",
    "emailDrive": "adindarapmayani888@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "ADINDA MANURUNG",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-65",
    "namaAllStaff": "ANDREY SHEVA TARIGAN",
    "nomorPasport": "E6037665",
    "jabatanPosisi": "KASIR",
    "emailDrive": "andreysheva070325@gmail.com",
    "emailBk": "andreysheva070325@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "ANDREYSHVTARIGAN",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-66",
    "namaAllStaff": "AKBAR REYNALDI MANIK",
    "nomorPasport": "X3353629",
    "jabatanPosisi": "KASIR",
    "emailDrive": "akbarreynaldi070325@gmail.com",
    "emailBk": "akbarreynaldi070325@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "PERBAUNGAN",
    "idLine": "AKBAR REYNALDI MANIK",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PERBAUNGAN",
    "notes": ""
  },
  {
    "id": "st-67",
    "namaAllStaff": "IMELDA LESTARI",
    "nomorPasport": "X4809279",
    "jabatanPosisi": "KASIR",
    "emailDrive": "imeldalestari070325@gmail.com",
    "emailBk": "imeldalestari070325@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "STABAT",
    "idLine": "IMELDA",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "STABAT",
    "notes": ""
  },
  {
    "id": "st-68",
    "namaAllStaff": "SUTIENO",
    "nomorPasport": "X2655440",
    "jabatanPosisi": "KASIR",
    "emailDrive": "sutienobold@gmail.com",
    "emailBk": "sutienobold@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "PONTIANAK",
    "idLine": "SUTIENO",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PONTIANAK",
    "notes": ""
  },
  {
    "id": "st-69",
    "namaAllStaff": "TEDY",
    "nomorPasport": "C7615156",
    "jabatanPosisi": "KASIR",
    "emailDrive": "tedynamthip@gmail.com",
    "emailBk": "tedynamthip@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "TEDY",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-70",
    "namaAllStaff": "YOLANDA LUBIS",
    "nomorPasport": "E7088470",
    "jabatanPosisi": "KASIR",
    "emailDrive": "yolandalubisbold88@gmail.com",
    "emailBk": "yolandalubisbold88@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "SIANTAR",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "SIANTAR",
    "notes": ""
  },
  {
    "id": "st-71",
    "namaAllStaff": "MELANI",
    "nomorPasport": "E4723253",
    "jabatanPosisi": "KASIR",
    "emailDrive": "melani240324@gmail.com",
    "emailBk": "melani240324@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Perempuan",
    "messTinggal": "MESS 85",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "MELANI",
    "seasonRumahIbadah": "SEASON 6",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-72",
    "namaAllStaff": "ANTONI",
    "nomorPasport": "C9740702",
    "jabatanPosisi": "KASIR",
    "emailDrive": "antoni9992227@gmail.com",
    "emailBk": "antoni9992227@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "TanjungPinang",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "TanjungPinang",
    "notes": ""
  },
  {
    "id": "st-73",
    "namaAllStaff": "L MANISA",
    "nomorPasport": "X1317828",
    "jabatanPosisi": "KASIR",
    "emailDrive": "Lmanisa817@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "",
    "idLine": "",
    "seasonRumahIbadah": "",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "",
    "notes": ""
  },
  {
    "id": "st-74",
    "namaAllStaff": "ADE SAEPUDIN",
    "nomorPasport": "E5582962",
    "jabatanPosisi": "KASIR",
    "emailDrive": "adedasani6@gmail.com",
    "emailBk": "",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "TANJUNG PINANG",
    "idLine": "ADESAEPUDIN",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "TANJUNG PINANG",
    "notes": ""
  },
  {
    "id": "st-75",
    "namaAllStaff": "MARTIN LESMANA",
    "nomorPasport": "E7722064",
    "jabatanPosisi": "KASIR",
    "emailDrive": "martinlesmana7788@gmail.com",
    "emailBk": "namtiplesman@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "PONTIANAK",
    "idLine": "",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "PONTIANAK",
    "notes": ""
  },
  {
    "id": "st-76",
    "namaAllStaff": "ARIEF FADLI WAHYU",
    "nomorPasport": "X4788021",
    "jabatanPosisi": "KASIR",
    "emailDrive": "arief.sadboy1122@gmail.com",
    "emailBk": "arief.fans.sadbor@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "KISARAN",
    "idLine": "ARIEF FADLI WAHYU",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "KISARAN",
    "notes": ""
  },
  {
    "id": "st-77",
    "namaAllStaff": "COCO FRAN SISCO",
    "nomorPasport": "X6958677",
    "jabatanPosisi": "KASIR",
    "emailDrive": "cocofransisco8899@gmail.com",
    "emailBk": "cocofransisco8899@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "LUBUK PAKAM",
    "idLine": "COCO",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "LUBUK PAKAM",
    "notes": ""
  },
  {
    "id": "st-78",
    "namaAllStaff": "FENDI CANDRA",
    "nomorPasport": "X2242324",
    "jabatanPosisi": "KASIR",
    "emailDrive": "fendi.wakwau88@gmail.com",
    "emailBk": "fendi.wakwau88@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "candrafend@gmail.com",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-79",
    "namaAllStaff": "SULISTIANI",
    "nomorPasport": "E7359416",
    "jabatanPosisi": "KASIR",
    "emailDrive": "sulis.wakwau88@gmail.com",
    "emailBk": "",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Perempuan",
    "messTinggal": "",
    "nomorKamar": "VIP",
    "asalKota": "LUBUK PAKAM",
    "idLine": "SULISTIANI",
    "seasonRumahIbadah": "SEASON 8",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "LUBUK PAKAM",
    "notes": ""
  },
  {
    "id": "st-80",
    "namaAllStaff": "RIZKY PRADANA NAIBAHO",
    "nomorPasport": "E2364836",
    "jabatanPosisi": "KASIR",
    "emailDrive": "rizkynamthip@gmail.com",
    "emailBk": "rizkynamthip@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "BINJAI",
    "idLine": "PRADANA",
    "seasonRumahIbadah": "SEASON 4",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "BINJAI",
    "notes": ""
  },
  {
    "id": "st-81",
    "namaAllStaff": "OKTOBERIUS HASRAT SETIAWAN GEA",
    "nomorPasport": "X2811533",
    "jabatanPosisi": "KASIR",
    "emailDrive": "geaoktaberius@gmail.com",
    "emailBk": "geaoktaberius@gmail.com",
    "status": "KERJA",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "MESS 52",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "oktoberius gea \"R'G2",
    "seasonRumahIbadah": "SEASON 5",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  },
  {
    "id": "st-82",
    "namaAllStaff": "GUNTUR ANUGRAH SEJATI",
    "nomorPasport": "E9670921",
    "jabatanPosisi": "KASIR",
    "emailDrive": "gntrsejati@gmail.com",
    "emailBk": "gntrsejati@gmail.com",
    "status": "DIRUMAHKAN",
    "jenisKelamin": "Laki-laki",
    "messTinggal": "LIMDA",
    "nomorKamar": "VIP",
    "asalKota": "MEDAN",
    "idLine": "GUNTUR",
    "seasonRumahIbadah": "SEASON 7",
    "tanggalLahir": "2026-06-14",
    "tanggalMulaiKerja": "2026-06-14",
    "expVisa": "",
    "typeVisa": "",
    "lokasiSaatIni": "MEDAN",
    "notes": ""
  }
];

export const SAMPLE_MISTAKES: any[] = [];
export const SAMPLE_OVERTIMES: OvertimeRecord[] = [];
